Test Fleet Updated

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -17,19 +17,38 @@ jobs:
           role-to-assume: arn:aws:iam::162168468250:role/github-action-deploy-role
           aws-region: us-east-1
 
-      - name: Print Private IPs
+      - name: Fleet Health Check
+        id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["hostname -I"]}' \
+            --parameters '{"commands":
+              "hostname -I"
+              "docker --version" 2>/dev/null || echo "Docker not installed"
+              "aws --version 2>/dev/null || echo "AWS CLI not installed"
+              "mysql --version 2>/dev/null || echo "MySQL not installed"
+              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region ap-northeast-2"]}' \
             --query 'Command.CommandId' --output text
+            --region ap-northeast-2)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_ENV
           )
-
-          sleep 30
+      - name: Show Results
+        run: |
+          
+          sleep 20
 
           aws ssm list-command-invocations \
-            --command-id "$CMD_ID" \
-            --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
-            --output table
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region ap-northeast-2 \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --output text
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region ap-northeast-2 \
+            --query "length(CommandInvocations[?Status==\`Failed\`])" \
+            --output text \
+            --region ap-northeast-2)
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health check failed for $FAILED instance(s)" && exit 1
+          echo "All Instances Are Healthy✅"
